### ISSUE TITLE
no module named 'diff_match_patch'

### ISSUE THREAD

**Issue by xdmiodz** [Stibbons/python-fiximports#3]
Hi,

First of all, thanks for the great plugin :)

sublime packages have been updated recently and your package became broken somehow, it shows the following error and doesn't work anymore

![screen shot 2015-03-11 at 14 54 11](https://cloud.githubusercontent.com/assets/563026/6595779/804d964e-c7fe-11e4-8f66-baf587f97344.png)

**Comment by gsemet** [comment]
Indeed. Thanks for the report. It should have worked because another package provided this lib as well. I add the lib within my package. Should be fixed by https://github.com/Stibbons/python-fiximports/releases/tag/1.0.11

Update pushed on Package Control :) This should arrive in 1-2 hours :)
