### ISSUE TITLE
feature request: fix and reorder selection only

### ISSUE THREAD

**Issue by cbillingham** [Stibbons/python-fiximports#9]
Thanks for this. This is super helpful.
Would be nice to have a fix selection option, so you could fix only selected lines.
I'll take a look at adding this if other people think it would be a useful feature.

**Comment by gsemet** [comment]
you mean a way in a project to select which files should be "fixed" and other not? When I have this case, I disable the auto fix, and fix manualy the file

**Comment by cbillingham** [comment]
No, I meant a way to reorder just the selected import statements in a single file. But I may have spoke too soon. Given that the tool already preserves import groupings the user has made, it's probably not a very useful option.

**Comment by gsemet** [comment]
yes, this was the goal of the "fix by group" feature. You can still have your manually placed import, for any reason, given the fact you leave an empty line before and after. I fall in this case quite often, that why i dont use other tools such as isort that much

**Comment by cbillingham** [comment]
Sounds good. Sorry I didn't check that first. Going to close this!
